<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BennyScraper</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Version>2.1.0</Version>
    <InformationalVersion>2.1.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Configuration" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" />
    <PackageReference Include="NLog" />
    <PackageReference Include="Selenium.WebDriver" />
    <PackageReference Include="SeleniumExtras.WaitHelpers" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Benny-Scraper.BusinessLogic\Benny-Scraper.BusinessLogic.csproj" />
    <ProjectReference Include="..\Benny-Scraper.DataAccess\Benny-Scraper.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\compose.yaml" Link="compose.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="sites\novelfire.net.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    01:16:58 Info Starting scraper for CommonStrategy with base uri:
    01:16:59 Info Cloudflare challenge detected for https://www.webnovel.com/book/the-adventures-of-an-overpowered-knight-in-another-world_31799923608237405. Switching to FlareSolverr.
    Title: The Adventures of an Overpowered Knight in Another World
    Author: Master_Rod
    Description line count: 22
    Total Genres: 10
    Genres: # R18, # SMUT, # ROMANCE, # HAREM, # OVERPOWERED, # ADVENTURE, # REINCARNATION, # MAGIC, # ACTION, # DARK
    ThumbnailUrl: https://book-pic.webnovel.com/bookcover/31799923608237405?imageMogr2/thumbnail/600x&amp;imageId=1770545145980
    01:19:49 Info Loading https://www.webnovel.com/book/31799923608237405/catalog directly with FlareSolverr because it was required earlier in this scraping session.
    01:19:51 Error Error scraping novel data from https://www.webnovel.com/book/the-adventures-of-an-overpowered-knight-in-another-world_31799923608237405 System.Net.CookieException: The 'Value'='{"i_l":0,"i_ll":1787552390524,"i_b":"UrzfFQRDbVy3I3RuL9aDTCxI1UaRQRqTEZr3BQ8ke7c","i_e":{"enable_itp_optimization":24},"i_et":1787552390524}' part of the cookie is invalid.
    at System.Net.Cookie.VerifyAndSetDefaults(CookieVariant variant, Uri uri)
    at System.Net.CookieContainer.Add(Uri uri, Cookie cookie)
    at BennyScraper.BusinessLogic.Factory.HttpClientFactory.AddCookiesFromHeader(Uri uri, String cookieHeader) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Factory\HttpClientFactory.cs:line 125
    at BennyScraper.BusinessLogic.Scrapers.Strategy.ScraperStrategy.TrySolveCloudflareChallengeAsync(Uri uri, Boolean cloudflareChallengeDetected) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\ScraperStrategy.cs:line 804
    at BennyScraper.BusinessLogic.Scrapers.Strategy.ScraperStrategy.LoadHtmlAsync(Uri uri) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\ScraperStrategy.cs:line 647
    at BennyScraper.BusinessLogic.Scrapers.Strategy.CommonStrategy.BuildNovelDataAsync(HtmlDocument htmlDocument, Uri novelUri) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\CommonStrategy.cs:line 73
    at BennyScraper.BusinessLogic.Scrapers.Strategy.CommonStrategy.ScrapeAsync() in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\CommonStrategy.cs:line 20
    01:19:51 Error Exception when trying to process novel with chapter range. System.Net.CookieException: The 'Value'='{"i_l":0,"i_ll":1787552390524,"i_b":"UrzfFQRDbVy3I3RuL9aDTCxI1UaRQRqTEZr3BQ8ke7c","i_e":{"enable_itp_optimization":24},"i_et":1787552390524}' part of the cookie is invalid.
    at System.Net.Cookie.VerifyAndSetDefaults(CookieVariant variant, Uri uri)
    at System.Net.CookieContainer.Add(Uri uri, Cookie cookie)
    at BennyScraper.BusinessLogic.Factory.HttpClientFactory.AddCookiesFromHeader(Uri uri, String cookieHeader) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Factory\HttpClientFactory.cs:line 125
    at BennyScraper.BusinessLogic.Scrapers.Strategy.ScraperStrategy.TrySolveCloudflareChallengeAsync(Uri uri, Boolean cloudflareChallengeDetected) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\ScraperStrategy.cs:line 804
    at BennyScraper.BusinessLogic.Scrapers.Strategy.ScraperStrategy.LoadHtmlAsync(Uri uri) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\ScraperStrategy.cs:line 647
    at BennyScraper.BusinessLogic.Scrapers.Strategy.CommonStrategy.BuildNovelDataAsync(HtmlDocument htmlDocument, Uri novelUri) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\CommonStrategy.cs:line 73
    at BennyScraper.BusinessLogic.Scrapers.Strategy.CommonStrategy.ScrapeAsync() in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\Scrapers\Strategy\CommonStrategy.cs:line 20
    at BennyScraper.BusinessLogic.NovelProcessor.AddNewNovelAsync(Uri novelTableOfContentsUri, ScraperStrategy scraperStrategy, Configuration configuration, Nullable`1 beginChapter, Nullable`1 endChapter) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\NovelProcessor.cs:line 662
    at BennyScraper.BusinessLogic.NovelProcessor.ProcessNovelAsync(Uri novelTableOfContentsUri, Nullable`1 beginChapter, Nullable`1 endChapter, Boolean withLogin, Boolean confirmPremiumChapters) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper.BusinessLogic\NovelProcessor.cs:line 73
    at BennyScraper.Program.HandleOptionsAsync(CommandLineOptions options) in C:\Users\Emiya\RiderProjects\Benny-Scraper\Benny-Scraper\Program.cs:line 357
    Error processing novel: The 'Value'='{"i_l":0,"i_ll":1787552390524,"i_b":"UrzfFQRDbVy3I3RuL9aDTCxI1UaRQRqTEZr3BQ8ke7c","i_e":{"enable_itp_optimization":24},"i_et":1787552390524}' part of the cookie is invalid.

    <None Update="sites\webnovel.com.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="sites\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
