<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BennyScraper.BusinessLogic</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Scrapers\Strategy\Attributes\**" />
    <EmbeddedResource Remove="Scrapers\Strategy\Attributes\**" />
    <None Remove="Scrapers\Strategy\Attributes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="NLog" />
    <PackageReference Include="Polly" />
    <PackageReference Include="RecursiveDataAnnotationsValidation" />
    <PackageReference Include="Selenium.WebDriver" />
    <PackageReference Include="SeleniumExtras.WaitHelpers" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="TextCopy" />
    <PackageReference Include="PdfSharp" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Benny-Scraper.DataAccess\Benny-Scraper.DataAccess.csproj" />
    <ProjectReference Include="..\Benny-Scraper.Models\Benny-Scraper.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Benny-Scraper" />
    <InternalsVisibleTo Include="Benny-Scraper.Tests" />
  </ItemGroup>

</Project>
